### ISSUE TITLE
missing line in minimalPkg.c

### ISSUE THREAD

**Issue by biloucat** [SynologyOpenSource/minimalPkg#1]
the line 
  ret = sysinfo(&info);
is missing in minimalPkg.c
why "EXEC= minimalPkg_2 in Makefile ???
should not be EXEC= minimalPkg    ???

**Comment by SynologyOpenSource** [comment]
Thanks for your reply. 

We will add `ret = sysinfo(&info);` into minimalPkg.c. Sorry for make this mistake.

In pkgscripts framework, we can cross-compile source code by 
1. Makefile + `include /env.mak`
2. SynoBuildConf/build
We need to demonstrate above two scripts in minimalPkg. In build script `SynoBuildConf/build`, we compile the minimalPkg first and then execute command `make ${MAKE_FLAG}`. If `Makefile` still uses minimalPkg as executable name, `make ${MAKE_FLAG}` will not really compile the binary.  So we change the example executable name to `minimalPkg_2` so that `make ${MAKE_FLAG}` will use the cross-compiler to compile the source.

In order to avoid other user confusing the executable name, we will adjust executable name and add the comment before it.

**Comment by biloucat** [comment]
Thanks, but who to contact to update the developer guide ?

**Comment by SynologyOpenSource** [comment]
Thanks for your reply.

We will update the developer guide later.
